import {catalogProducts,categories,filterProducts,familyMatches,equivalentReferences,minimumInterval,normalized,reviewedAt} from './catalog-data-v2721.mjs';
import {stagesV2699,pipelinesV2699,encodeOpportunityV2699,decodeOpportunityV2699} from './opportunity-fields-v2699.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Number(v).toLocaleString('fr-CA',{maximumFractionDigits:8});
const $=(s,r=document)=>r.querySelector(s),all=(s,r=document)=>[...r.querySelectorAll(s)];
const missing='Non renseigné par la source';
const link=(url,label)=>url?'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+'</a>':'';
export function opportunityTabs(view='create'){return '<nav class="cdq-opportunity-tabs" aria-label="Menu des opportunités"><button type="button" data-opportunity-view="create" data-new-op aria-pressed="'+(view==='create')+'">Créer une opportunité</button><button type="button" data-opportunity-view="manage" aria-pressed="'+(view==='manage')+'">Gestion des opportunités</button></nav>';}
export function productFacts(p){const min=minimumInterval(p);return [
 ['Capacité',p.capacity!=null?fmt(p.capacity)+' '+p.unit:missing],['Matériau',p.material||missing],['Signal nominal',p.output?fmt(p.output)+' mV/V':missing],
 ['Divisions NTEP — une cellule',p.ntepSingle?fmt(p.ntepSingle):missing],['Divisions NTEP — plusieurs cellules',p.ntepMultiple?fmt(p.ntepMultiple):missing],
 ['Résolution d’affichage (d)',p.readability!=null?fmt(p.readability)+' '+p.unit:p.displayDivisions?fmt(p.displayDivisions)+' divisions (affichage)':missing],
 ['Intervalle minimal de cellule (vmin)',min?fmt(min.value)+' '+min.unit+' — '+min.method:missing],['Certificat NTEP',p.certNumber||((p.ntepSingle||p.ntepMultiple)?'Voir les homologations du fabricant':missing)],
 ['Classe de certification',p.certificationClass||missing],['Protection',p.ip||missing],['Résistance d’entrée',p.inputOhms||missing],['Résistance de sortie',p.outputOhms||missing],['Excitation',p.excitation||missing],['Surcharge admissible',p.overload||missing],['Dimensions',p.dimensions||missing]
 ];}
export function inventoryForProduct(p,inventory){return (inventory?.articles||[]).filter(a=>{
 const candidates=familyMatches(a);if(!candidates.some(q=>q.familyId===p.familyId))return false;
 if(candidates.length===1)return true;
 const raw=[a.modele,a.numero,a.description].join(' '),unit=p.unit==='lb'?'(?:lb|lbs|livres?)':p.unit==='kg'?'(?:kg|kilogrammes?)':'g';
 return p.capacity!=null&&new RegExp('(?:^|[^0-9])'+String(p.capacity).replace('.','[.,]')+'\\s*'+unit+'(?:$|[^a-z])','i').test(raw);
 });}
export function ganttRange(items,days=60,today=new Date().toISOString().slice(0,10)){const valid=items.map(i=>i.dateReception).filter(d=>/^\d{4}-\d{2}-\d{2}$/.test(d)),base=valid.length?valid.sort()[0]:today;return {start:base,days};}
export function shiftDate(date,delta){const d=new Date(date+'T12:00:00Z');if(!Number.isFinite(d.getTime()))throw Error('Date invalide.');d.setUTCDate(d.getUTCDate()+delta);return d.toISOString().slice(0,10);}
export function shiftedSchedule(item,delta,{endOnly=false}={}){if(!item.dateReception||!item.dateCloture)throw Error('Indiquez une date de réception et une date de clôture avant de déplacer la période.');const dateReception=endOnly?item.dateReception:shiftDate(item.dateReception,delta),dateCloture=shiftDate(item.dateCloture,delta);if(dateCloture<dateReception)throw Error('La clôture doit suivre la réception.');return {...item,dateReception,dateCloture};}
export function opportunityRank(item){if(Number.isFinite(item.boardOrder))return item.boardOrder;let hash=0;for(const c of String(item.id||''))hash=(Math.imul(hash,31)+c.charCodeAt(0))>>>0;const date=Date.parse((item.dateReception||'')+'T12:00:00Z');return (Number.isFinite(date)?date:0)+hash%1000000;}
export function commercialIcon(key,theme='current'){
 const paths={catalog:'<path d="M5 7l11-3 11 3v21l-11-3-11 3zM16 4v21M8 11l5-1m-5 6 5-1m7-3 4 1m-4 4 4 1"/>',opportunityBoard:'<rect x="3" y="4" width="26" height="24" rx="3"/><path d="M11 8v17M21 8v17M6 10h2v5H6zm8 2h4v5h-4zm10 5h2v6h-2z"/>',root:'<path d="M4 14L16 4l12 10M8 12v16h16V12M13 28v-9h6v9"/>',refresh:'<path d="M27 12A12 12 0 006 7L3 11m0-8v8h8M5 20a12 12 0 0021 5l3-4m0 8v-8h-8"/>'};
 if(!paths[key])return '';
 const metal=theme==='metal-music',isometric=theme==='isometric',minimal=theme==='minimal',dark=theme==='dark-pro';
 const color=key==='catalog'?'#c77dff':key==='opportunityBoard'?'#21e966':'#4cd9ff';
 const gradient='<defs><linearGradient id="cdq-'+key+'-metal" x2=".2" y2="1"><stop stop-color="#f7fcff"/><stop offset=".32" stop-color="#6a7c92"/><stop offset=".55" stop-color="#18253b"/><stop offset=".8" stop-color="#a3b7ca"/><stop offset="1" stop-color="#273245"/></linearGradient></defs>';
 return '<svg data-icon-theme="'+esc(theme)+'" data-commercial-icon="'+key+'" viewBox="0 0 32 32" aria-hidden="true" fill="none" stroke="'+(metal?color:'currentColor')+'" stroke-width="'+(minimal?1.7:2)+'" stroke-linejoin="round" stroke-linecap="round">'+(metal?gradient+'<g fill="url(#cdq-'+key+'-metal)">':dark?'<rect x="1" y="1" width="30" height="30" rx="6" fill="#111a24" stroke="#71899f"/><g transform="translate(3 3) scale(.81)" stroke="'+color+'">':isometric?'<g transform="matrix(.83,.1,-.1,.83,4,1)" fill="#203e54" stroke="'+color+'">':'<g>')+paths[key]+'</g></svg>';
}
export function createCommercialWorkspace(api){
 let board=null,catalog=null,criteria={},boardCriteria={},selected=null,view='board',epoch=0,scope='',busy=new Set(),inventory=null,inventoryScope='',inventoryReadAt=0,inventoryLoading=null;
 const ensureScope=()=>{if(scope!==api.owner()){reset();scope=api.owner();}};
 const message=(p,s,error=false)=>{if(!p||!p.isConnected)return;let e=$('[data-commercial-status]',p);if(!e){e=document.createElement('p');e.dataset.commercialStatus='';e.role='status';$('.cdq-workspace-body',p).append(e);}e.textContent=s;e.className='cdq-workspace-status'+(error?' cdq-workspace-error':'');};
 function reset(){epoch++;scope='';view='board';all('.cdq-commercial-dialog').forEach(d=>d.remove());busy.clear();inventory=null;inventoryScope='';inventoryReadAt=0;inventoryLoading=null;criteria={};boardCriteria={};selected=null;board?.remove();catalog?.remove();board=catalog=null;}
 async function getInventory(force=false){if(!api.canRead())throw Error('Accès à l’inventaire requis.');const owner=api.owner(),read=window.cdqInventoryModernV2592?.cachedRead;if(!read&&!force&&inventoryScope===owner&&inventory&&Date.now()-inventoryReadAt<30000)return inventory;if(inventoryLoading?.owner===owner)return inventoryLoading.promise;
  const promise=(read?read(force):api.rpc('cdqInventoryGetV2593')).then(r=>{if(owner!==api.owner()||!api.canRead())throw Error('Le compte a changé.');inventory=r?.inventory||r;inventoryScope=owner;inventoryReadAt=Date.now();return inventory;}).finally(()=>{if(inventoryLoading?.owner===owner)inventoryLoading=null;});inventoryLoading={owner,promise};return promise;}
 function navInventory(id){api.navigate('inventory');Promise.resolve(window.cdqInventoryModernV2592?.openArticle?.(id)).catch(e=>message(catalog,e.message,true));}
 function stock(p){const current=inventory||window.cdqInventoryModernV2592?.snapshot?.(),rows=inventoryForProduct(p,current);if(!current)return '<p>Stock : chargement…</p>';if(!rows.length)return '<p>Aucun article associé à cette variante dans l’inventaire.</p>';
  return rows.map(a=>{const movements=(current.stock||current.stocks||[]).filter(x=>String(x.articleId)===String(a.articleId)),units=(current.unites||[]).filter(x=>String(x.articleId)===String(a.articleId));let summary=movements.map(x=>esc(x.emplacementNom||x.emplacementId)+': '+fmt(x.quantite??x.qty??0)).join(' · ');if(!summary)summary='Ouvrir l’article pour voir le stock par emplacement';return '<div class="cdq-catalog-stock"><strong>'+esc(a.numero||a.modele)+'</strong><p>'+summary+'</p><p>Prix client : '+(a.prixClient==null?'Non renseigné':fmt(a.prixClient)+' CAD')+'</p><button type="button" data-inventory-article="'+esc(a.articleId)+'">Ouvrir dans Inventaire</button></div>';}).join('');}
 function detailHtml(p,{embedded=false}={}){const facts=productFacts(p),equivalents=equivalentReferences(p);return '<section class="cdq-product-detail"><div class="cdq-product-title">'+commercialIcon('catalog',api.theme())+'<div><small>'+esc(p.brand)+' · '+esc(p.category)+'</small><h3>'+esc(p.model)+(p.capacity?' · '+fmt(p.capacity)+' '+p.unit:'')+'</h3></div></div><p>'+esc(p.summary)+'</p>'+(p.status?'<p>'+esc(p.status)+'</p>':'')+'<dl class="cdq-specs">'+facts.slice(0,8).map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl><details><summary>Afficher complet</summary><dl class="cdq-specs">'+facts.slice(8).map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl><p>'+link(p.source,'Fiche fabricant')+' '+link(p.datasheet,'Fiche technique complète')+' '+link(p.certSource,'Certificat / homologations')+'</p><p class="cdq-workspace-hint">Source revue le '+reviewedAt+'. Les divisions certifiées et la résolution d’affichage sont présentées séparément.</p></details>'+(equivalents.length?'<section><h4>Références interchangeables</h4><p>Références du fabricant; vérifier la variante, le montage et le certificat avant remplacement.</p><div class="cdq-equivalents">'+equivalents.map(q=>'<button type="button" data-equivalent="'+esc(q.products[0]?.id||'')+'">'+esc(q.brand)+' · '+esc(q.model)+'</button>').join('')+'</div>'+(p.interchangeNote?'<p>'+esc(p.interchangeNote)+'</p>':'')+link(p.source,'Source des équivalences')+'</section>':'')+(embedded?'':'<section><h4>Inventaire et prix client</h4>'+stock(p)+'</section>')+'</section>';}
 function bindDetail(container){all('[data-equivalent]',container).forEach(b=>b.onclick=()=>{selected=b.dataset.equivalent;api.navigate('catalog');renderCatalog();});all('[data-inventory-article]',container).forEach(b=>b.onclick=()=>navInventory(b.dataset.inventoryArticle));}
 function enrichArticle(a,container){const models=familyMatches(a);if(!models.length)return;let block=document.createElement('section');block.className='cdq-im-section cdq-catalog-enrichment';const exact=models.length===1?models[0]:models.find(p=>inventoryForProduct(p,{articles:[a]}).length);block.innerHTML='<h3>Fiche technique du catalogue</h3>'+(models.length>1?'<label>Variante / capacité<select data-catalog-variant><option value="">Choisir la variante exacte</option>'+models.map(p=>'<option value="'+esc(p.id)+'" '+(exact?.id===p.id?'selected':'')+'>'+esc(p.model)+(p.capacity?' · '+fmt(p.capacity)+' '+p.unit:'')+'</option>').join('')+'</select></label>':'')+'<div data-variant-detail>'+(exact?detailHtml(exact,{embedded:true}):'<p>Choisissez la capacité de l’article pour afficher ses données certifiées.</p>')+'</div>';container.querySelector('.cdq-im-desc')?.after(block);const select=$('[data-catalog-variant]',block);if(select)select.onchange=()=>{const p=catalogProducts.find(x=>x.id===select.value);$('[data-variant-detail]',block).innerHTML=p?detailHtml(p,{embedded:true}):'';bindDetail(block);};bindDetail(block);}
 function renderCatalog(){if(!catalog||catalog.hidden||!api.canRead())return;const body=$('.cdq-workspace-body',catalog);if(selected){const p=catalogProducts.find(x=>x.id===selected);if(!p){selected=null;return renderCatalog();}body.innerHTML='<button type="button" data-catalog-back>Retour aux résultats</button>'+detailHtml(p);$('[data-catalog-back]',body).onclick=()=>{selected=null;renderCatalog();};bindDetail(body);return;}
  body.innerHTML='<div class="cdq-catalog-layout"><details class="cdq-catalog-filters" open><summary>Affiner la recherche</summary><label>Rechercher<input type="search" data-filter="query" placeholder="Fabricant, modèle, type"></label>'+[['category','Famille'],['brand','Fabricant'],['capacity','Capacité'],['material','Matériau'],['application','Usage de la certification'],['divisions','Divisions NTEP minimales'],['output','Signal (mV/V)'],['readability','Échelon d’affichage (d)']].map(([key,title])=>'<label>'+title+'<select data-filter="'+key+'"></select></label>').join('')+'<button type="button" data-clear-filters>Réinitialiser</button></details><div><p data-count role="status"></p><div class="cdq-catalog-grid" data-catalog-results></div></div></div>';
  $('[data-clear-filters]',body).onclick=()=>{criteria={};renderCatalog();};all('[data-filter]',body).forEach(el=>{if(el.tagName==='INPUT'){el.value=criteria.query||'';el.oninput=()=>{criteria.query=el.value;refreshResults();};}else el.onchange=()=>{criteria[el.dataset.filter]=el.value;refreshResults();};});refreshResults();}
 function refreshResults(){const body=$('.cdq-workspace-body',catalog);for(const el of all('select[data-filter]',body)){const key=el.dataset.filter,c={...criteria};delete c[key];const available=filterProducts(catalogProducts,c);let values;
   if(key==='application')values=[['multiple','Plusieurs cellules'],['single','Une cellule']];else if(key==='divisions')values=[3000,5000,6000,9500,10000].map(n=>[String(n),fmt(n)+' et plus']);else values=[...new Set(available.map(p=>key==='capacity'?p.capacity!=null?p.capacity+' '+p.unit:'':key==='readability'?p.readability!=null?p.readability+' '+p.unit:'':String(p[key]??'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{numeric:true})).map(v=>[v,v]);
   const current=String(criteria[key]||'');if(current&&!values.some(([v])=>v===current))values.push([current,current+' (0 résultat)']);el.innerHTML=(key==='application'?'':'<option value="">Tous</option>')+values.map(([value,label])=>'<option value="'+esc(value)+'">'+esc(label)+'</option>').join('');el.value=current|| (key==='application'?'multiple':'');}
  const products=filterProducts(catalogProducts,criteria);$('[data-count]',body).textContent=products.length+' variante(s) · '+new Set(products.map(p=>p.familyId)).size+' modèle(s)';const grid=$('[data-catalog-results]',body);grid.innerHTML=products.map(p=>'<button class="cdq-product-card" type="button" data-product="'+esc(p.id)+'">'+commercialIcon('catalog',api.theme())+'<small>'+esc(p.brand)+'</small><strong>'+esc(p.model)+'</strong><span>'+esc(p.capacity!=null?fmt(p.capacity)+' '+p.unit:'Variantes dans la fiche fabricant')+'</span><span>'+esc(p.material||p.category)+'</span><span>'+(p.ntepMultiple?'NTEP M : '+fmt(p.ntepMultiple)+' divisions':p.readability!=null?'d : '+fmt(p.readability)+' '+p.unit:'')+'</span></button>').join('')||'<p>Aucun résultat. Retirez un filtre pour élargir la recherche.</p>';all('[data-product]',grid).forEach(b=>b.onclick=()=>{selected=b.dataset.product;renderCatalog();});}
 async function openCatalog(){ensureScope();catalog=api.page('cdqCatalogPageV2721','Catalogue','Produits, fiches techniques et équivalences');catalog.hidden=false;if(!api.canRead()){message(catalog,'Accès requis à l’application.');return;}renderCatalog();const owner=api.owner();try{await getInventory(false);if(owner===api.owner())renderCatalog();}catch(e){if(owner===api.owner())message(catalog,e.message,true);}}
 function rank(item){return opportunityRank(item);}
 function boardItems(){return api.getOpportunities().filter(i=>(!boardCriteria.boardQuery||normalized([i.titre,i.clientNom,i.contact,i.responsable].join(' ')).includes(normalized(boardCriteria.boardQuery)))&&(!boardCriteria.pipeline||i.pipeline===boardCriteria.pipeline)).sort((a,b)=>rank(a)-rank(b)||a.titre.localeCompare(b.titre,'fr'));}
 async function save(item,changes){const owner=api.owner();if(scope!==owner||!api.canWrite())throw Error('Modification non autorisée pour ce compte.');if(busy.has(owner+'|'+item.id))throw Error('Enregistrement déjà en cours.');busy.add(owner+'|'+item.id);try{const payload=encodeOpportunityV2699({...item,...changes,expectedRevision:item.revision,requestId:'op-'+crypto.randomUUID()},{existing:true}),r=await api.rpc('cdqEnregistrerOpportuniteV2638',payload);if(!r?.ok||!r.item)throw Error('Enregistrement non confirmé.');if(owner!==api.owner()||!api.canRead())throw Error('Le compte a changé.');epoch++;api.updateOpportunity(decodeOpportunityV2699(r.item));return r.item;}finally{busy.delete(owner+'|'+item.id);}}
 async function move(id,stage,beforeId){const item=api.getOpportunities().find(x=>String(x.id)===String(id));if(!item||!stagesV2699.includes(stage))return;const peers=boardItems().filter(x=>x.etape===stage&&x.id!==item.id),index=beforeId?peers.findIndex(x=>String(x.id)===String(beforeId)):peers.length,prev=index>0?rank(peers[index-1]):peers[index]?rank(peers[index])-2000:0,next=peers[index]?rank(peers[index]):prev+2000;try{await save(item,{etape:stage,boardOrder:(prev+next)/2});renderBoard();message(board,'Modification enregistrée.');}catch(e){message(board,e.message,true);renderBoardCards();}}
 function card(item){return '<article class="cdq-op-card" tabindex="0" draggable="'+api.canWrite()+'" data-op-card="'+esc(item.id)+'"><div class="cdq-op-cardtop"><strong>'+esc(item.titre)+'</strong><button type="button" data-drag-handle aria-label="Déplacer cette opportunité" '+(!api.canWrite()?'disabled':'')+'>⠿</button></div><p>'+esc(item.clientNom)+'</p><p>'+esc(item.contact||'')+'</p><small>'+esc(item.responsable||'')+'</small><p>'+ (item.montant?fmt(item.montant)+' CAD':'Valeur à préciser')+'</p><small>'+esc(item.dateReception||'')+(item.dateCloture?' → '+esc(item.dateCloture):'')+'</small><label>Étape<select data-card-stage '+(!api.canWrite()?'disabled':'')+'>'+stagesV2699.map(t=>'<option '+(t===item.etape?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select></label><button type="button" data-card-edit '+(!api.canWrite()?'disabled':'')+'>Dates et détails</button></article>';}
 function renderBoardCards(){if(!board||board.hidden)return;const main=$('[data-board]',board);if(!main)return;const items=boardItems();if(view==='gantt'){renderGantt(main,items);return;}main.className='cdq-kanban';main.innerHTML=stagesV2699.map((stage,index)=>{const column=items.filter(i=>i.etape===stage);return '<section class="cdq-kanban-column" data-stage="'+esc(stage)+'"><header><strong>'+esc(stage)+'</strong><span>'+column.length+'</span><small>'+fmt(column.reduce((n,i)=>n+Number(i.montant||0),0))+' CAD</small></header><div class="cdq-kanban-cards">'+column.map(card).join('')+'</div></section>';}).join('');bindCards(main);
  all('[data-stage]',main).forEach(col=>{col.ondragover=e=>{if(!api.canWrite())return;e.preventDefault();e.dataTransfer.dropEffect='move';};col.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-cdq-opportunity'),before=e.target.closest('[data-op-card]')?.dataset.opCard;if(id)move(id,col.dataset.stage,before);};});}
 function bindCards(main){all('[data-op-card]',main).forEach(el=>{const id=el.dataset.opCard,item=api.getOpportunities().find(i=>String(i.id)===id);el.ondragstart=e=>{if(!api.canWrite()){e.preventDefault();return;}e.dataTransfer.setData('application/x-cdq-opportunity',id);e.dataTransfer.effectAllowed='move';};$('[data-card-stage]',el).onchange=e=>move(id,e.target.value);$('[data-card-edit]',el).onclick=()=>edit(item);const handle=$('[data-drag-handle]',el);handle.onpointerdown=e=>{if(e.pointerType==='mouse'||!api.canWrite())return;let moved=false;handle.setPointerCapture(e.pointerId);const old=handle.style.touchAction;handle.style.touchAction='none';handle.onpointermove=ev=>{moved=true;const hit=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('[data-stage]');all('.cdq-drop-target',main).forEach(x=>x.classList.remove('cdq-drop-target'));hit?.classList.add('cdq-drop-target');};handle.onpointerup=ev=>{const hit=document.elementFromPoint(ev.clientX,ev.clientY),col=hit?.closest('[data-stage]');handle.onpointermove=handle.onpointerup=null;handle.style.touchAction=old;all('.cdq-drop-target',main).forEach(x=>x.classList.remove('cdq-drop-target'));if(moved&&col)move(id,col.dataset.stage,hit.closest('[data-op-card]')?.dataset.opCard);};handle.onpointercancel=()=>{handle.onpointermove=handle.onpointerup=null;handle.style.touchAction=old;all('.cdq-drop-target',main).forEach(x=>x.classList.remove('cdq-drop-target'));};};});}
 function edit(item){if(!api.canWrite())return;const editOwner=api.owner(),dialog=document.createElement('dialog');dialog.className='cdq-commercial-dialog';dialog.innerHTML='<form method="dialog"><h3>'+esc(item.titre)+'</h3><label>Réception<input name="dateReception" type="date" value="'+esc(item.dateReception||'')+'" required></label><label>Clôture<input name="dateCloture" type="date" value="'+esc(item.dateCloture||'')+'"></label><label>Prochain suivi<input name="suivi" type="date" value="'+esc(item.suivi||'')+'"></label><label>Responsable<input name="responsable" value="'+esc(item.responsable||'')+'" maxlength="120"></label><label>Notes<textarea name="notes" maxlength="1300">'+esc(item.notes||'')+'</textarea></label><p role="status"></p><div><button type="button" data-cancel>Annuler</button><button type="submit">Enregistrer</button></div></form>';document.body.append(dialog);$('[data-cancel]',dialog).onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();$('form',dialog).onsubmit=async e=>{e.preventDefault();const changes=Object.fromEntries(new FormData(e.target)),button=$('[type=submit]',dialog);button.disabled=true;try{if(editOwner!==api.owner())throw Error('Le compte a changé.');if(changes.dateCloture&&changes.dateCloture<changes.dateReception)throw Error('La clôture doit suivre la réception.');await save(item,changes);dialog.close();renderBoard();message(board,'Modification enregistrée.');}catch(err){if(!dialog.isConnected)return;$('[role=status]',dialog).textContent=err.message;button.disabled=false;}};dialog.showModal();}
 function renderGantt(main,items){const days=Number(boardCriteria.days||60),range={...ganttRange(items,days),...(boardCriteria.ganttStart?{start:boardCriteria.ganttStart}:{})},dayWidth=24,labelWidth=window.innerWidth<600?160:260;main.className='cdq-gantt';main.innerHTML='<p>Déplacez une période pour modifier ses dates. La poignée droite ajuste la clôture.</p><div class="cdq-gantt-scroll"><div class="cdq-gantt-scale" style="width:'+ (labelWidth+days*dayWidth)+'px"><div class="cdq-gantt-dates" style="margin-left:'+labelWidth+'px">'+Array.from({length:days},(_,i)=>'<span style="width:'+dayWidth+'px">'+esc(shiftDate(range.start,i).slice(8))+(i%7===0?'<small>'+esc(shiftDate(range.start,i).slice(0,7))+'</small>':'')+'</span>').join('')+'</div>'+items.map(i=>{const start=i.dateReception&&i.dateCloture?Math.floor((Date.parse(i.dateReception)-Date.parse(range.start))/86400000):null,end=start==null?0:Math.floor((Date.parse(i.dateCloture)-Date.parse(range.start))/86400000),width=Math.max(dayWidth,(end-start+1)*dayWidth);return '<div class="cdq-gantt-row"><button data-gantt-edit="'+esc(i.id)+'">'+esc(i.titre)+'<small>'+esc(i.clientNom)+'</small></button><div class="cdq-gantt-track" style="width:'+days*dayWidth+'px">'+(start==null?'<button data-gantt-edit="'+esc(i.id)+'">Définir les dates</button>':'<div class="cdq-gantt-bar" tabindex="0" role="button" aria-label="Période de '+esc(i.titre)+'" data-gantt-id="'+esc(i.id)+'" style="left:'+start*dayWidth+'px;width:'+width+'px"><span>'+esc(i.etape)+'</span><button data-gantt-resize aria-label="Ajuster la date de clôture">↔</button></div>')+'</div></div>';}).join('')+'</div></div>';
  all('[data-gantt-edit]',main).forEach(b=>b.onclick=()=>edit(items.find(i=>String(i.id)===b.dataset.ganttEdit)));
  all('[data-gantt-id]',main).forEach(bar=>{const item=items.find(i=>String(i.id)===bar.dataset.ganttId);bar.onkeydown=e=>{if(e.key==='Enter')edit(item);};bar.onpointerdown=e=>{if(!api.canWrite())return;e.preventDefault();bar.setPointerCapture(e.pointerId);const x=e.clientX,endOnly=!!e.target.closest('[data-gantt-resize]');let delta=0;bar.onpointermove=ev=>{delta=Math.round((ev.clientX-x)/dayWidth);bar.style.transform=endOnly?'':'translateX('+delta*dayWidth+'px)';if(endOnly)bar.style.width=Math.max(dayWidth,parseFloat(bar.dataset.oldWidth|| (bar.dataset.oldWidth=bar.style.width))+delta*dayWidth)+'px';};bar.onpointerup=async()=>{bar.onpointermove=bar.onpointerup=null;if(!delta){edit(item);return;}try{const next=shiftedSchedule(item,delta,{endOnly});await save(item,{dateReception:next.dateReception,dateCloture:next.dateCloture});renderBoard();message(board,'Modification enregistrée.');}catch(err){renderBoardCards();message(board,err.message,true);}};bar.onpointercancel=()=>{bar.onpointermove=bar.onpointerup=null;renderBoardCards();};};});}
 function renderBoard(){if(!board||board.hidden||!api.canRead())return;const body=$('.cdq-workspace-body',board);body.innerHTML=opportunityTabs('manage')+'<div class="cdq-commercial-toolbar"><button data-board-view="board" aria-pressed="'+(view==='board')+'">Par étapes</button><button data-board-view="gantt" aria-pressed="'+(view==='gantt')+'">Gantt</button><input type="search" data-board-search aria-label="Rechercher une opportunité" placeholder="Client, projet, contact" value="'+esc(boardCriteria.boardQuery||'')+'"><select data-pipeline aria-label="Pipeline"><option value="">Tous les pipelines</option>'+pipelinesV2699.map(p=>'<option '+(p===boardCriteria.pipeline?'selected':'')+'>'+esc(p)+'</option>').join('')+'</select><select data-days aria-label="Période du Gantt">'+[30,60,90,180].map(d=>'<option value="'+d+'" '+(d===Number(boardCriteria.days||60)?'selected':'')+'>'+d+' jours</option>').join('')+'</select><label>Début du Gantt<input type="date" data-gantt-start value="'+esc(boardCriteria.ganttStart||ganttRange(boardItems()).start)+'"></label><button data-board-refresh>Actualiser</button></div><div data-board></div><p data-commercial-status role="status"></p>';
  $('[data-opportunity-view=create]',body).onclick=()=>api.navigate('opportunities');$('[data-opportunity-view=manage]',body).onclick=()=>{};all('[data-board-view]',body).forEach(b=>b.onclick=()=>{view=b.dataset.boardView;renderBoard();});$('[data-board-search]',body).oninput=e=>{boardCriteria.boardQuery=e.target.value;renderBoardCards();};$('[data-pipeline]',body).onchange=e=>{boardCriteria.pipeline=e.target.value;renderBoardCards();};$('[data-days]',body).onchange=e=>{boardCriteria.days=Number(e.target.value);renderBoardCards();};$('[data-gantt-start]',body).onchange=e=>{boardCriteria.ganttStart=e.target.value;renderBoardCards();};$('[data-board-refresh]',body).onclick=loadBoard;renderBoardCards();}
 async function loadBoard(){const generation=++epoch,owner=api.owner(),dataEpoch=api.opportunityEpoch();message(board,'Chargement des opportunités…');try{const r=await api.rpc('cdqListerOpportunitesV2638');if(generation!==epoch||dataEpoch!==api.opportunityEpoch()||owner!==api.owner()||!api.canRead())return;api.setOpportunities((r.items||[]).map(decodeOpportunityV2699));renderBoard();message(board,api.getOpportunities().length+' opportunité(s)');}catch(e){if(generation===epoch&&owner===api.owner())message(board,e.message,true);}}
 function openBoard(){ensureScope();board=api.page('cdqOpportunityBoardV2721','Opportunités','Gestion des opportunités · Étapes et Gantt');board.hidden=false;if(!api.canRead()){message(board,'Accès Drive requis.');return;}renderBoard();loadBoard();}
 window.cdqCatalogV2721={enrichArticle,products:catalogProducts};
 return {openCatalog,openBoard,reset,renderBoard,renderCatalog};
}
